from datetime import datetime, timezone
from typing import Optional, Union as PyUnion, Annotated, Literal
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from .common_types import (
    CommandAckStatus,
    SpecificErrorCode,
    MODEL_CONFIG_WITH_DATETIME_ENCODER,
)


model_config = {
    **MODEL_CONFIG_WITH_DATETIME_ENCODER,  # Use shared constant
    "populate_by_name": True,
    "allow_population_by_field_name": True,
}


class BaseD2CMessage(BaseModel):
    message_id: UUID = Field(
        default_factory=uuid4,
        description="Unique ID for this D2C message instance.",
    )
    timestamp_utc: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        alias="timestamp",
        description="Timestamp when the message was generated by the drone (UTC).",
    )
    version: Literal["1.0"] = "1.0"
    message_type_d2c: str = Field(
        ..., alias="type", description="Discriminator: Type of the D2C message."
    )

    model_config = {
        **MODEL_CONFIG_WITH_DATETIME_ENCODER,
        "populate_by_name": True,
        "allow_population_by_field_name": True,
    }


class BaseCommandAckPayload(BaseD2CMessage):
    message_type_d2c: Literal["command_ack"] = Field("command_ack", alias="type")
    command_id: UUID = Field(
        ...,
        alias="command_id",
        description="The ID of the command this acknowledgement is for.",
    )


class CommandAckNominal(BaseCommandAckPayload):
    status: Literal[
        CommandAckStatus.RECEIVED,
        CommandAckStatus.EXECUTED,
    ]


class CommandAckFailure(BaseCommandAckPayload):
    status: Literal[CommandAckStatus.ERROR,]
    error_code: SpecificErrorCode = Field(
        ...,
        description="A machine-readable error code if the command failed or was rejected.",
    )
    error_message: Optional[str] = Field(
        None,
        alias="message",
        description="A human-readable message providing more details about an error.",
    )


CommandAcknowledgementUnion = Annotated[
    PyUnion[CommandAckNominal, CommandAckFailure], Field(discriminator="status")
]


AllDroneToCloudV1Messages = Annotated[
    PyUnion[CommandAcknowledgementUnion], Field(discriminator="message_type_d2c")
]
